version: "3.8"

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootPassword
      MYSQL_DATABASE: LagediDB
      MYSQL_USER: userDB
      MYSQL_PASSWORD: passwordDB
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"

  php-nginx:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db

  frontend:
    image: node:18
    working_dir: /usr/src/app
    volumes:
      - ./frontend:/usr/src/app
    command: ["tail", "-f", "/dev/null"]

volumes:
  db_data: